/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnitest */

#ifndef _Included_jnitest
#define _Included_jnitest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnitest
 * Method:    setNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnitest_setNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnitest
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnitest_getNumber
  (JNIEnv *, jobject);

/*
 * Class:     jnitest
 * Method:    cpp_ctor
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jnitest_cpp_1ctor
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnitest
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnitest_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
