/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machinelearning_util_Math */

#ifndef _Included_machinelearning_util_Math
#define _Included_machinelearning_util_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_util_Math
 * Method:    eigen
 * Signature: ([[Ljava/lang/Float;)Lmachinelearning/util/Eigen;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Math_eigen___3_3Ljava_lang_Float_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     machinelearning_util_Math
 * Method:    eigen
 * Signature: ([[Ljava/lang/Double;)Lmachinelearning/util/Eigen;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Math_eigen___3_3Ljava_lang_Double_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     machinelearning_util_Math
 * Method:    svd
 * Signature: ([[Ljava/lang/Float;[Ljava/lang/Float;[[Ljava/lang/Float;[[Ljava/lang/Float;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_util_Math_svd___3_3Ljava_lang_Float_2_3Ljava_lang_Float_2_3_3Ljava_lang_Float_2_3_3Ljava_lang_Float_2
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     machinelearning_util_Math
 * Method:    svd
 * Signature: ([[Ljava/lang/Double;[Ljava/lang/Double;[[Ljava/lang/Double;[[Ljava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_util_Math_svd___3_3Ljava_lang_Double_2_3Ljava_lang_Double_2_3_3Ljava_lang_Double_2_3_3Ljava_lang_Double_2
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     machinelearning_util_Math
 * Method:    perronfrobenius
 * Signature: ([[Ljava/lang/Float;I)[Ljava/lang/Float;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_util_Math_perronfrobenius___3_3Ljava_lang_Float_2I
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     machinelearning_util_Math
 * Method:    perronfrobenius
 * Signature: ([[Ljava/lang/Double;I)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_util_Math_perronfrobenius___3_3Ljava_lang_Double_2I
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
