/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machinelearning_util_Random */

#ifndef _Included_machinelearning_util_Random
#define _Included_machinelearning_util_Random
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_util_Random
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_util_Random_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    getFloat
 * Signature: (Lmachinelearning/util/Random/Distribution;)Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_getFloat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    get
 * Signature: (Lmachinelearning/util/Random/Distribution;Ljava/lang/Float;)Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_get__Lmachinelearning_util_Random_Distribution_2Ljava_lang_Float_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    get
 * Signature: (Lmachinelearning/util/Random/Distribution;Ljava/lang/Float;Ljava/lang/Float;)Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_get__Lmachinelearning_util_Random_Distribution_2Ljava_lang_Float_2Ljava_lang_Float_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    get
 * Signature: (Lmachinelearning/util/Random/Distribution;Ljava/lang/Float;Ljava/lang/Float;Ljava/lang/Float;)Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_get__Lmachinelearning_util_Random_Distribution_2Ljava_lang_Float_2Ljava_lang_Float_2Ljava_lang_Float_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    getDouble
 * Signature: (Lmachinelearning/util/Random/Distribution;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_getDouble
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    get
 * Signature: (Lmachinelearning/util/Random/Distribution;Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_get__Lmachinelearning_util_Random_Distribution_2Ljava_lang_Double_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    get
 * Signature: (Lmachinelearning/util/Random/Distribution;Ljava/lang/Double;Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_get__Lmachinelearning_util_Random_Distribution_2Ljava_lang_Double_2Ljava_lang_Double_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    get
 * Signature: (Lmachinelearning/util/Random/Distribution;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_machinelearning_util_Random_get__Lmachinelearning_util_Random_Distribution_2Ljava_lang_Double_2Ljava_lang_Double_2Ljava_lang_Double_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     machinelearning_util_Random
 * Method:    cppCtor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_util_Random_cppCtor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_util_Random_Distribution */

#ifndef _Included_machinelearning_util_Random_Distribution
#define _Included_machinelearning_util_Random_Distribution
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
