############################################################################
# LGPL License                                                             #
#                                                                          #
# This file is part of the Machine Learning Framework.                     #
# Copyright (c) 2010, Philipp Kraus, <philipp.kraus@flashpixx.de>          #
# This program is free software: you can redistribute it and/or modify     #
# it under the terms of the GNU Lesser General Public License as           #
# published by the Free Software Foundation, either version 3 of the       #
# License, or (at your option) any later version.                          #
#                                                                          #
# This program is distributed in the hope that it will be useful,          #
# but WITHOUT ANY WARRANTY; without even the implied warranty of           #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
# GNU Lesser General Public License for more details.                      #
#                                                                          #
# You should have received a copy of the GNU Lesser General Public License #
# along with this program. If not, see <http://www.gnu.org/licenses/>.     #
############################################################################
 
# -*- coding: utf-8 -*-

import os
Import("*")

buildlist = []

if env["withfiles"] :
    buildlist.append( env.Program( target=os.path.join("#build", "lda"), source=defaultcpp+["lda.cpp"] ) )
    buildlist.append( env.Program( target=os.path.join("#build", "mds"), source=defaultcpp+["mds.cpp"] ) )
    buildlist.append( env.Program( target=os.path.join("#build", "pca"), source=defaultcpp+["pca.cpp"] ) )
    
env.Alias( "reducing", buildlist )