/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machinelearning_dimensionreduce_nonsupervised_MDS */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_MDS
#define _Included_machinelearning_dimensionreduce_nonsupervised_MDS
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
#define _Included_machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    getDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    setIteration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_setIteration
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    setStep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_setStep
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    setRate
 * Signature: (Ljava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_setRate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    setCentering
 * Signature: (Lmachinelearning/dimensionreduce/nonsupervised/MDS/Centeroption;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_setCentering
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    map
 * Signature: ([[Ljava/lang/Double;)[[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_map
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateDouble
 * Method:    cppCtor
 * Signature: (ILmachinelearning/dimensionreduce/nonsupervised/MDS/Project;)J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateDouble_cppCtor
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
#define _Included_machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    getDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    setIteration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_setIteration
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    setStep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_setStep
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    setRate
 * Signature: (Ljava/lang/Float;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_setRate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    setCentering
 * Signature: (Lmachinelearning/dimensionreduce/nonsupervised/MDS/Centeroption;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_setCentering
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    map
 * Signature: ([[Ljava/lang/Float;)[[Ljava/lang/Float;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_map
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_MDS_DelegateFloat
 * Method:    cppCtor
 * Signature: (ILmachinelearning/dimensionreduce/nonsupervised/MDS/Project;)J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_dimensionreduce_nonsupervised_MDS_00024DelegateFloat_cppCtor
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_MDS_Strategy */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_MDS_Strategy
#define _Included_machinelearning_dimensionreduce_nonsupervised_MDS_Strategy
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_MDS_Centeroption */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_MDS_Centeroption
#define _Included_machinelearning_dimensionreduce_nonsupervised_MDS_Centeroption
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_MDS_Project */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_MDS_Project
#define _Included_machinelearning_dimensionreduce_nonsupervised_MDS_Project
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
