/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machinelearning_dimensionreduce_nonsupervised_mds */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_mds
#define _Included_machinelearning_dimensionreduce_nonsupervised_mds
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_mds_delegate_double */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
#define _Included_machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    getDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    setIteration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_setIteration
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    setStep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_setStep
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    setRate
 * Signature: (Ljava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_setRate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    setCentering
 * Signature: (Lmachinelearning/dimensionreduce/nonsupervised/mds/centeroption;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_setCentering
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    map
 * Signature: ([[Ljava/lang/Double;)[[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_map
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_double
 * Method:    cpp_ctor
 * Signature: (ILmachinelearning/dimensionreduce/nonsupervised/mds/project;)J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1double_cpp_1ctor
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_mds_delegate_float */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
#define _Included_machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    getDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    setIteration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_setIteration
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    setStep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_setStep
  (JNIEnv *, jobject, jint);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    setRate
 * Signature: (Ljava/lang/Float;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_setRate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    setCentering
 * Signature: (Lmachinelearning/dimensionreduce/nonsupervised/mds/centeroption;)V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_setCentering
  (JNIEnv *, jobject, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    map
 * Signature: ([[Ljava/lang/Float;)[[Ljava/lang/Float;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_map
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_mds_delegate_float
 * Method:    cpp_ctor
 * Signature: (ILmachinelearning/dimensionreduce/nonsupervised/mds/project;)J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_dimensionreduce_nonsupervised_mds_00024delegate_1float_cpp_1ctor
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_mds_Strategy */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_mds_Strategy
#define _Included_machinelearning_dimensionreduce_nonsupervised_mds_Strategy
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_mds_centeroption */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_mds_centeroption
#define _Included_machinelearning_dimensionreduce_nonsupervised_mds_centeroption
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_mds_project */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_mds_project
#define _Included_machinelearning_dimensionreduce_nonsupervised_mds_project
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
