/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machinelearning_dimensionreduce_nonsupervised_pca */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_pca
#define _Included_machinelearning_dimensionreduce_nonsupervised_pca
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca
 * Method:    map
 * Signature: ([[)[[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_map
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca
 * Method:    getDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca
 * Method:    cpp_ctor
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_cpp_1ctor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
