/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machinelearning_dimensionreduce_nonsupervised_pca */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_pca
#define _Included_machinelearning_dimensionreduce_nonsupervised_pca
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_pca_delegate_double */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_pca_delegate_double
#define _Included_machinelearning_dimensionreduce_nonsupervised_pca_delegate_double
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_double
 * Method:    getDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1double_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_double
 * Method:    map
 * Signature: ([[Ljava/lang/Double;)[[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1double_map
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_double
 * Method:    getProject
 * Signature: ()[[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1double_getProject
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_double
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1double_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_double
 * Method:    cpp_ctor
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1double_cpp_1ctor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_pca_delegate_float */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_pca_delegate_float
#define _Included_machinelearning_dimensionreduce_nonsupervised_pca_delegate_float
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_float
 * Method:    getDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1float_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_float
 * Method:    map
 * Signature: ([[Ljava/lang/Float;)[[Ljava/lang/Float;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1float_map
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_float
 * Method:    getProject
 * Signature: ()[[Ljava/lang/Float;
 */
JNIEXPORT jobjectArray JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1float_getProject
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_float
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1float_dispose
  (JNIEnv *, jobject);

/*
 * Class:     machinelearning_dimensionreduce_nonsupervised_pca_delegate_float
 * Method:    cpp_ctor
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_machinelearning_dimensionreduce_nonsupervised_pca_00024delegate_1float_cpp_1ctor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class machinelearning_dimensionreduce_nonsupervised_pca_Strategy */

#ifndef _Included_machinelearning_dimensionreduce_nonsupervised_pca_Strategy
#define _Included_machinelearning_dimensionreduce_nonsupervised_pca_Strategy
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
